language: php
php:
  - 7.4
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - public_html/vendor/bin/phpunit --testsuite Unit  --stderr -c phpunit.xml