#!/usr/bin/env bash

isRunning=false
workspaceId=$(docker-compose ps -q osm-app)
if [[ -n "$workspaceId" ]] && docker ps -q --no-trunc | grep -q "${workspaceId}"; then
  isRunning=true
fi

start() {
  docker-compose up -d --force-recreate
  isRunning=true
}

stop-all() {
    echo "Stopping all containers";
    docker stop $(docker ps -a -q)
}

stop() {
  echo "Removing containers"
  docker-compose down --remove-orphans
  isRunning=false
}

build() {
  echo "Building..."
  docker-compose build --force-rm
}

restart() {
  stop
  start
}

ssh() {
  if [[ "$isRunning" == false ]]; then
    start
  fi

  echo "Connecting to workspace"

  docker exec -it osm bash
}

if [[ -n "$1" ]]; then
  command="$1"
  if [[ -n "$(type -t "${command}")" ]] && [[ "$(type -t "${command}")" == function ]]; then
    "$command" "${@:2}"
    exit
  else
    echo "Command not found"
    exit
  fi
fi