version: "3"
services:
  osm-app:
    container_name: osm
    build:
      context: ./
      dockerfile: ./docker-conf/PHPAPACHE.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - ./docker-conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: osm
      MYSQL_ROOT_PASSWORD: admin
volumes:
  data:
