version: "3"
services:
  osm-app:
    container_name: osm
    build:
      context: ./
      dockerfile: ./docker-conf/PHPAPACHE.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public_html:/var/www/html
    networks:
      - default
    depends_on:
      - db
  db:
    build:
      context: ./
      dockerfile: ./docker-conf/MySQL.Dockerfile
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - persistent:/var/lib/mysql
      - ./docker-conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - default
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: osm
      MYSQL_ROOT_PASSWORD: admin
volumes:
  persistent:
